[27.03.2019 16:01:24.601] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:01:32.527] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:02:09.157] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:02:19.042] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:02:48.638] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:02:50.889] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:02:59.887] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:03:19.540] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:03:33.903] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:04:06.395] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:04:16.355] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:10:30.844] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:10:48.740] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:11:29.058] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:23:30.405] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:23:31.943] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:49:41.341] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:49:49.005] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:49:56.790] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:54:31.853] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:54:41.430] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:58:25.221] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 16:58:33.158] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 17:00:53.662] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 17:00:59.181] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 17:02:45.825] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
[27.03.2019 17:03:27.434] [System.Data.Entity.Internal.InternalContext.SaveChanges()] An error occurred while updating the entries. See the inner exception for details.    в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Time.View_model.Index_View_Model.SaveStatisticSite() в D:\Documents\GitHub\Exam_f\Time\Time\View_model\Index_View_Model.cs:строка 325
